### ISSUE TITLE
Good existing mouse gesture recognition application for Linux

### ISSUE THREAD

**Issue by MRWITEK** [HawaiinPizza/Rational-Operating-System-Shell#10]
I think this is a good example of very usable "GUI" that is out of your way when you are not using it.
https://github.com/markdstjohn/easystroke
![image](https://user-images.githubusercontent.com/3463397/84833554-37db5680-b038-11ea-9dae-b0fbc8f22241.png)

* Pretty good recognition for gestures in a wide range of complexity -- from a straight line to a star
* Separate gesture configurations for different applications with an option to disable recognition in unknown programs, with combining of gesture sets by overlaying (setting up the combinations seems to be half-broken)
* Separate gestures for every (up to 12) mouse button with ability to use modifier keys (Shift, Alt, Control, Super)
* Recognized gestures execute a specified command or send to an affected application a preset key combination, text or mouse button click

**Comment by HawaiinPizza** [comment]
Interesting idea: will use this technology in a future project, but not in this one. We're making a menu wheel.
